updated yaml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -79,16 +79,24 @@ jobs:
         EOF
 
     # Transfer files to EC2
+    # Debug file existence
+    - name: Debug file existence
+      run: |
+        echo "Listing current directory files:"
+        ls -la
+        echo "Displaying contents of .env:"
+        cat .env || echo ".env file not found"
+
+    # Transfer files to EC2
     - name: Transfer files to EC2
       uses: appleboy/scp-action@v0.1.7
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ubuntu
         key: ${{ secrets.EC2_SSH_KEY }}
-        source: |
-          .env
-          docker-compose.yml
+        source: ./.env,./docker-compose.yml
         target: /home/ubuntu/
+
 
     # Ensure necessary folders exist on EC2
     - name: Prepare EC2 environment
